In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
from scipy.stats import ortho_group

In [2]:
d = 16
seed = 1
size = 2
a, b = np.float32(ortho_group.rvs(size=size, dim=d, random_state=seed))  # 生成一个随机16*16正交矩阵，可以改变随机数seed种子更改

In [3]:
matrix = a[[0,1,2]]
matrix                  # matrix为正交矩阵前三行

array([[ 0.33575377,  0.43329155,  0.24143682, -0.2660712 ,  0.04576025,
         0.16139346, -0.04778346, -0.18954928, -0.30891657,  0.27911475,
        -0.24736853, -0.34801942, -0.3000195 ,  0.17227027,  0.16828583,
        -0.02088279],
       [-0.12645064,  0.02099939, -0.30562544,  0.04577005, -0.05411398,
         0.25931713, -0.37818864,  0.16842304, -0.06155179,  0.11445536,
        -0.32817397, -0.16838738,  0.46830863, -0.19863822,  0.43594766,
        -0.21151644],
       [-0.10917361,  0.28032652,  0.01775413,  0.22409584,  0.04557591,
         0.1688271 ,  0.24962476, -0.3612034 , -0.5061129 , -0.00924787,
         0.14013588,  0.18903157,  0.29504102, -0.3905146 , -0.04072028,
         0.28772914]], dtype=float32)

In [4]:
comb = np.random.RandomState(123456789).rand(10000,3)*10
comb  

array([[5.32833025, 5.34136601, 5.09553036],
       [7.13564032, 2.56998955, 7.52693609],
       [8.83879184, 1.54899083, 6.70546438],
       ...,
       [8.53396931, 1.11147291, 3.89342635],
       [4.12107057, 9.79348953, 8.70269822],
       [4.00564021, 6.5708399 , 3.31918883]])

In [5]:
data = matrix.T @ comb.T 
data 

array([[ 0.55729035,  1.24909851,  2.03972703, ...,  2.29970648,
        -0.80483306,  0.15165404],
       [ 3.84929822,  5.25578068,  5.74202119, ...,  4.81246773,
         4.43087949,  2.80405037],
       [-0.2555355 ,  1.07098634,  1.7796485 , ...,  1.78984444,
        -1.84365252, -0.98217747],
       ...,
       [-2.13296559, -2.22061799, -1.40360956, ..., -0.2710717 ,
        -4.63395417, -1.91135894],
       [ 3.01774704,  2.01470911,  1.88967394, ...,  1.76214871,
         4.60859026,  3.40347644],
       [ 0.22507547,  1.47311177,  1.41714188, ...,  0.70694436,
         0.34647642, -0.51846224]])

In [6]:
result = pd.DataFrame(data.T)
result.head()

0         1         2         3         4         5         6   \
0  0.557290  3.849298 -0.255535 -0.031354  0.187017  3.105329 -1.002679   
1  1.249099  5.255781  1.070986 -0.094205  0.530503  3.088839  0.566003   
2  2.039727  5.742021  1.779649 -0.778184  0.626251  2.960267  0.665691   
3  0.427950  5.038826 -0.525146  0.297044  0.244097  4.179019 -1.175133   
4  2.620618  3.577219  1.677672 -2.125142  0.323207  1.580976 -0.752538   

         7         8         9         10        11        12        13  \
0 -1.950895 -4.553694  2.051441 -2.356892 -1.790565  2.406195 -2.132966   
1 -3.638465 -6.171984  2.216203 -1.553743 -1.493267  1.283472 -2.220618   
2 -3.836537 -6.219514  2.582316 -1.755101 -2.069357  0.051983 -1.403610   
3 -2.705312 -6.222509  2.554939 -2.917204 -2.042484  3.667394 -3.252817   
4 -1.399487 -2.606880  2.396419 -2.341159 -3.006851 -1.986802  1.201752   

         14        15  
0  3.017747  0.225075  
1  2.014709  1.473112  
2  1.889674  1.417142  
3  3.932580  0.489341  
4  1.802882 -0.367803

In [7]:
result.to_csv("newresult.csv")

In [8]:
label = pd.DataFrame(comb)
label.columns = ['one','two','three']
label['func'] = np.sin(label['one']*label['two']) + label['three']**3


#label.apply(lambda x: np.sin(x['one']*x['two']) + x['three']**3)

In [9]:
label.to_csv('newlabel.csv')

In [10]:
print(np.sin(0.532833*0.534137) + 0.509553**3)

0.4130816616666104


In [11]:
label['func'].max()

1000.2588709298699

In [12]:
label['func'].min()

-0.9988388450000579

In [13]:
1.77**2

3.1329000000000002

In [14]:
0.08**0.5


0.282842712474619

In [15]:
0.28/1.77

0.15819209039548024